### PR TITLE
CI: Change back GitHub release to template

### LINKED ISSUE #64: Linux releases should use musl
Since the switch to Azure Pipelines for the CI, the Linux release build is not using musl anymore. See for example the first working release [v0.1.10.2](https://github.com/nbigaouette/pycors/releases/tag/v0.1.10.2).

The linux build should include at the minimum a musl build which is fully static.

### PR DESCRIPTION
**Pull request by nbigaouette**
This changes the GitHub release CI config to use the template. This allows targeting many different platforms, including a static build using musl under Linux.

Closes #64.

### CODE REVIEW

**Comment by xoac** [comment]
```
repositoryName: xoac/rust-azure-pipelines
```
should be:
```
    repositoryName: nbigaouette/pycors
```

And you also need a `PipelinesTemplates` connection in your azure settings. You can specify other name but it has to write access to your repo. [Here](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#sep-github) you find more information I will add some info to REAME soon.

**Comment by nbigaouette** [comment]
Hum... so adding back `repositoryName` did not fix the issue...

When you talk about `PipelinesTemplates`, I think you already have something in your README.md? I did follow it (see attached screenshot) (I use the same `PipelinesTemplates` name). Is that what you meant?

The release to github process was working for previous versions; Only in the PR where the template is used does the release fail...

Screen Shot 2019-05-09 at 1 57 27 PM

**Comment by xoac** [comment]
Unfortunately I did this repo to learn Azure pipelines, so I am not master of this.
This is how roles look like:

obraz

I see the strange info:
```
No releases are published yet in the repository.
Fetching the initial commit...
```
You have at this moment 26 releases. So it looks strange. 

For now I am out of ideas what going on.

**Comment by nbigaouette** [comment]
My releases were not made from the template. I looked at the template and wanted to tweak it so I implemented it myself (based on your template of course). I wanted to use native builds instead going through `cross`. See for example how it looks on master: https://github.com/nbigaouette/pycors/blob/1ad94ab9fda1c05c8792c890f6a59e1f3f35666d/azure-pipelines.yml#L148-L217. The 26 releases were done using this.

The current PR is to re-introduce the usage of the templates.

I was also surprised to see the strings `No releases are published yet in the repository.` and `Fetching the initial commit...`. There seems to be something wrong when Azure attempts to get the commits between the last release. Looking [at the code](https://github.com/microsoft/azure-pipelines-tasks/blob/b2608105c535e8cdf3f62d41425d18a83b70a006/Tasks/GitHubReleaseV0/operations/ChangeLog.ts#L38-L55) suggests that this is not working properly...

**Comment by nbigaouette** [comment]
I might have found the problem.

In the template file `ci/github-release.yml` there is a bunch of `repositoryName: xoac/rust-azure-pipelines`. For example: https://github.com/xoac/rust-azure-pipelines/blob/f037607d79eed048c3a39d73556f5b876b665e49/ci/github-release.yml#L60
Is that expected? Shouldn't the release be done on the template user's repo (and _not_ `xoac/rust-azure-pipelines`)?

According to the [Azure docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops), the `Repository` argument is described as:
> (Required) Select the name of GitHub repository in which GitHub releases will be created.

Those should probably be changed to `repositoryName: '$(Build.Repository.Name)'` instead, or at least provide an option.

**Comment by xoac** [comment]
So the problem was with `repositoryName` but not only in your code but also in mine. Thanks for catching this.

**Pull request merged**
